export const mockCampaigns = [
  {
    id: 1,
    title: "Decentralized Energy Grid",
    description: "Building a peer-to-peer energy trading platform using blockchain technology.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 45.8,
    target: 100,
    progress: 45,
    backers: 128,
  },
  {
    id: 2,
    title: "NFT Marketplace for Artists",
    description: "A platform for artists to mint and sell their digital creations as NFTs with minimal fees.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 32.5,
    target: 50,
    progress: 65,
    backers: 210,
  },
  {
    id: 3,
    title: "DeFi Lending Protocol",
    description: "A decentralized lending platform with innovative collateralization mechanisms.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 120.3,
    target: 200,
    progress: 60,
    backers: 315,
  },
  {
    id: 4,
    title: "Blockchain Gaming Platform",
    description: "Play-to-earn games with true ownership of in-game assets.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 85.2,
    target: 150,
    progress: 56,
    backers: 423,
  },
  {
    id: 5,
    title: "Decentralized Identity Solution",
    description: "Self-sovereign identity management using blockchain technology.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 28.7,
    target: 75,
    progress: 38,
    backers: 94,
  },
  {
    id: 6,
    title: "DAO Governance Tool",
    description: "A suite of tools for managing decentralized autonomous organizations.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 42.1,
    target: 60,
    progress: 70,
    backers: 156,
  },
  {
    id: 7,
    title: "Cross-Chain Bridge",
    description: "Seamlessly transfer assets between different blockchain networks.",
    image: "/placeholder.svg?height=300&width=500",
    raised: 95.4,
    target: 120,
    progress: 79,
    backers: 287,
  },
]
